apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-alumnos-frontend
  namespace: app-alumnos
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app-alumnos-frontend
  template:
    metadata:
      labels:
        app: app-alumnos-frontend
    spec:
      containers:
        - name: frontend
          image: 919889862541.dkr.ecr.us-east-1.amazonaws.com/app-alumnos-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5